### ISSUE TITLE
Null Pointer Exception when receiving a block

### ISSUE THREAD

**Issue by sigkill** [kncgroup/bitcoin-wallet#1]
Received output from a block today - the application now crashes every time. Can't get it to start on Android 4.4

**Comment by sigkill** [comment]
java.lang.NullPointerException
    at com.kncwallet.wallet.ui.TransactionsListAdapter.bindView(TransactionsListAdapter.java:342)
    at com.kncwallet.wallet.ui.TransactionsListAdapter.getView(TransactionsListAdapter.java:210)
    at android.widget.AbsListView.obtainView(AbsListView.java:2263)
    at android.widget.ListView.makeAndAddView(ListView.java:1790)
    at android.widget.ListView.fillDown(ListView.java:691)
    at android.widget.ListView.fillFromTop(ListView.java:752)
    at android.widget.ListView.layoutChildren(ListView.java:1616)
    at android.widget.AbsListView.onLayout(AbsListView.java:2091)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1589)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1589)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1589)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14824)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
    at android.view.Choreographer.doFrame(Choreographer.java:544)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5081)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by sigkill** [comment]
Clearing cache allows it to briefly start and then crash again - may be related to how the BTC is displayed?

**Comment by sigkill** [comment]
--- collected at 2014-03-18 19:32:17 -0700 on version 0.9.3 (7)
java.lang.RuntimeException: wallet/blockchain out of sync: 291241/291242
    at com.kncwallet.wallet.service.BlockchainServiceImpl$3.check(BlockchainServiceImpl.java:390)
    at com.kncwallet.wallet.service.BlockchainServiceImpl$3.onReceive(BlockchainServiceImpl.java:354)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5081)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by sigkill** [comment]
Removed the blockchain file - resyncing it now.

**Comment by sigkill** [comment]
Was able to copy and chown the files from "files" to the standard non-knc bitcoin wallet application directory on my rooted phone and load the wallet in the bitcoin application just fine.

**Comment by rcknight** [comment]
Thanks for the detailed report, will look into this tonight.

**Comment by sigkill** [comment]
Thanks! For what it's worth the block is still getting confirmations now!

--Bob

---

The information contained in this message, and any attachments, may contain
confidential and legally privileged material. It is solely for the use of
the person or entity to which it is addressed. Any review, retransmission,
dissemination, or action taken in reliance upon this information by persons
or entities other than the intended recipient is prohibited. If you receive
this in error, please contact the sender and delete the material from any
computer.

**Comment by aecole** [comment]
This was fixed some time ago

**Comment by sigkill** [comment]
Thank you
